# Generated by Django 4.2.3 on 2023-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subjectmark_percentage_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=152, primary_key=True, serialize=False),
        ),
    ]
