# Generated by Django 4.2.3 on 2023-07-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectmark',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=812, primary_key=True, serialize=False),
        ),
    ]
