# Generated by Django 4.2.3 on 2023-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_subjectmark_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=563, primary_key=True, serialize=False),
        ),
    ]
