# Generated by Django 4.2.3 on 2023-10-07 15:36

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=myapp.models.generate_unique_id, primary_key=True, serialize=False),
        ),
    ]
